---
apiVersion: "extensions/v1beta1"
kind: "DaemonSet"
metadata:
  labels:
    app: {{ template "linkerd.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "linkerd.fullname" . }}
spec:
  template:
    metadata:
      annotations:
        ## See https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md
        ##   #automatically-roll-deployments-when-configmaps-or-se  crets-change
        checksum/config: {{ include (print $.Chart.Name "/templates/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "linkerd.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      volumes:
        - name: {{ template "linkerd.fullname" . }}
          configMap:
            name: {{ template "linkerd.fullname" . }}
      hostNetwork: {{ default false .Values.pod.hostNetwork }}
      hostPID: {{ default false .Values.pod.hostPID }}
      containers:
        # The kubectl container, required
        - name: "kubectl"
          image: {{ .Values.kubectl.pod.image | quote }}
          args:
            - "proxy"
            - "--port"
            - "8001"
        - name: "linkerd"
          env:
            - name: "POD_IP"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
          image: {{ .Values.pod.image | quote }}
          args:
            - "/io.buoyant/linkerd/config/config.yaml"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: 4141
              hostPort: 4141
              protocol: "TCP"
              name: "incoming"
            - containerPort: 4140
              hostPort: 4140
              protocol: "TCP"
              name: "outgoing"
            - containerPort: 9990
              hostPort: 9990
              protocol: "TCP"
              name: "admin"
          volumeMounts:
            - name: {{ template "linkerd.fullname" . }}
              readOnly: true
              mountPath: "/io.buoyant/linkerd/config"
          livenessProbe:
            tcpSocket:
              port: "admin"
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: "admin"
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
      ## See http://kubernetes.io/docs/user-guide/pod-states/#restartpolicy
      restartPolicy: "Always"
