---
kind: "Service"
apiVersion: "v1"
metadata:
  annotations:
    prometheus.io/scrape: "{{ .Values.monitoring.service.scrape }}"
    {{ if eq .Values.service.type "LoadBalancer" }}service.beta.kubernetes.io/external-traffic: "OnlyLocal"{{ end }}
  labels:
    app: {{ template "linkerd.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "linkerd.fullname" . }}
spec:
  selector:
    app: {{ template "linkerd.fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
    - protocol: "__CONTAINER_PORT_PROTOCOL__"
      name: "__CONTAINER_PORT_NAME__"
      port: __CONTAINER_PORT__
  type: {{ default "ClusterIP" .Values.service.type }}
  {{ if eq .Values.service.type "LoadBalancer" -}}
  {{ if .Values.service.loadBalancer.publicIp -}}
  loadBalancerIP: {{ .Values.service.loadBalancer.publicIp }}
  {{ if .Values.service.loadBalancer.allowedIps -}}
  loadBalancerSourceRanges:
{{ .Values.service.loadBalancer.allowedIps | toYaml | indent 4 }}
  {{ end -}}
  {{ end -}}
  {{ end -}}
