---
kind: "Service"
apiVersion: "v1"
metadata:
  annotations:
    ## These annontations mark the service as monitorable by Prometheus, both directly as a service level metric and
    ## via the blackbox exporter. For more information, see
    ## values.yaml
    prometheus.io/scrape: {{ .Values.monitoring.service.scrape | quote }}
    prometheus.io/probe: {{ .Values.monitoring.service.probe | quote }}
    prometheus.io/path: {{ .Values.monitoring.service.path | quote }}
    prometheus.io/port: "9990"
  labels:
    app: {{ template "linkerd.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "linkerd.fullname" . }}
spec:
  selector:
    app: {{ template "linkerd.fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
    - containerPort: 4141
      port: 4141
      protocol: "TCP"
      name: "Incoming"
    - containerPort: 4140
      port: 4140
      protocol: "TCP"
      name: "Outgoing"
    - containerPort: 9990
      port: 9990
      protocol: "TCP"
      name: "Admin"
  type: "ClusterIP"
