---
kind: "Service"
apiVersion: "v1"
metadata:
  annotations:
    ## These annontations mark the service as monitorable by Prometheus, both directly as a service level metric and
    ## via the blackbox exporter. For more information, see
    ## values.yaml
    prometheus.io/scrape: {{ .Values.monitoring.service.scrape | quote }}
    prometheus.io/probe: {{ .Values.monitoring.service.probe | quote }}
    prometheus.io/path: {{ .Values.monitoring.service.path | quote }}
    prometheus.io/port: "9990"
  labels:
    app: {{ template "linkerd.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "linkerd.fullname" . }}
spec:
  selector:
    app: {{ template "linkerd.fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
    - protocol: "__CONTAINER_PORT_PROTOCOL__"
      name: "__CONTAINER_PORT_NAME__"
      port: __CONTAINER_PORT__
  type: {{ default "ClusterIP" .Values.service.type }}
  {{ if eq .Values.service.type "LoadBalancer" -}}
  {{ if .Values.service.loadBalancer.publicIp -}}
  loadBalancerIP: {{ .Values.service.loadBalancer.publicIp }}
  {{ if .Values.service.loadBalancer.allowedIps -}}
  loadBalancerSourceRanges:
{{ .Values.service.loadBalancer.allowedIps | toYaml | indent 4 }}
  {{ end -}}
  {{ end -}}
  {{ end -}}
